# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170111_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinedUsers',
            new_name='JoinedUser',
        ),
    ]
