# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20170111_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joineduser',
            unique_together=set([('user', 'room')]),
        ),
    ]
