# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('location', models.CharField(blank=True, choices=[('G', '\uacbd\uae30\ub3c4'), ('A', '\uac15\uc6d0\ub3c4'), ('Q', '\ucda9\uccad\ubd81\ub3c4'), ('R', '\ucda9\uccad\ub0a8\ub3c4'), ('Y', '\uacbd\uc0c1\ubd81\ub3c4'), ('Z', '\uacbd\uc0c1\ub0a8\ub3c4'), ('G', '\uc804\ub77c\ubd81\ub3c4'), ('H', '\uc804\ub77c\ub0a8\ub3c4'), ('S', '\uc11c\uc6b8'), ('I', '\uc778\ucc9c'), ('D', '\ub300\uc804'), ('J', '\uc138\uc885'), ('G', '\ub300\uad6c'), ('B', '\ubd80\uc0b0'), ('W', '\uad11\uc8fc'), ('J', '\uc81c\uc8fc')], max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('tag', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together=set([('tag', 'user')]),
        ),
    ]
