# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170109_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='greeting_message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
