# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_greeting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('G', '\uacbd\uae30\ub3c4'), ('A', '\uac15\uc6d0\ub3c4'), ('Q', '\ucda9\uccad\ubd81\ub3c4'), ('R', '\ucda9\uccad\ub0a8\ub3c4'), ('Y', '\uacbd\uc0c1\ubd81\ub3c4'), ('Z', '\uacbd\uc0c1\ub0a8\ub3c4'), ('K', '\uc804\ub77c\ubd81\ub3c4'), ('H', '\uc804\ub77c\ub0a8\ub3c4'), ('S', '\uc11c\uc6b8'), ('I', '\uc778\ucc9c'), ('D', '\ub300\uc804'), ('O', '\uc138\uc885'), ('P', '\ub300\uad6c'), ('B', '\ubd80\uc0b0'), ('W', '\uad11\uc8fc'), ('J', '\uc81c\uc8fc')], max_length=1, null=True),
        ),
    ]
